version: "3.7"

x-default-opts: 
  &default-opts
  logging:
    options:
      max-size: "50m"

networks:
  ntw_front:
    external: true

volumes:
  vol_couchdb:

services:

  swarmpit:
    <<: *default-opts
    image: swarmpit/swarmpit:latest
    environment:
      - SWARMPIT_DB=http://db:5984
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - ntw_front
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 1024M
        reservations:
          cpus: '0.25' 
          memory: 512M
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.backend=swarmpit"
        - "traefik.frontend.rule=PathPrefixStrip:/swarmpit"
        - "traefik.port=888"
        - "traefik.enable=true"
        - "traefik.docker.network=ntw_front"
        - "traefik.backend.loadbalancer.swarm=true"
        - "traefik.backend.loadbalancer.method=drr"

  db:
    <<: *default-opts
    image: couchdb:2.3.0
    volumes:
      - vol_couchdb:/opt/couchdb/data
    networks:
      - ntw_front
    deploy:
      resources:
        limits:
          cpus: '0.30'
          memory: 512M
        reservations:
          cpus: '0.15'
          memory: 256M
      placement:
        constraints:
          - node.labels.swarmpit.db-data == true

  agent:
    <<: *default-opts
    image: swarmpit/agent:latest
    environment:
      - DOCKER_API_VERSION=1.35
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - ntw_front
    deploy:
      mode: global
      resources:
        limits:
          cpus: '0.10'
          memory: 64M
        reservations:
          cpus: '0.05'
          memory: 32M
