version: '3.7'

x-default-opts: 
  &default-opts
  logging:
    options:
      max-size: "10m" 

networks:
  ntw_front:
    external: true

services:

  whoami1:
    <<: *default-opts
    image: containous/whoami
    networks:
      - ntw_front
    deploy:
      mode: replicated
      replicas: 2
      #placement:
      #  constraints: [node.role==manager]
      restart_policy:
        condition: on-failure
        max_attempts: 10
      resources:
        limits:
          cpus: '0.20'
          memory: 8M
        reservations:
          cpus: '0.05'
          memory: 4M
      labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami-secure.entrypoints=https"
      - "traefik.http.routers.whoami-secure.tls.certresolver=myhttpchallenge"
      - "traefik.http.routers.whoami-secure.rule=PathPrefixStrip(`/whoami1`)"
