version: "3.7"

x-default-opts: 
  &default-opts
  logging:
    options:
      max-size: "50m" 

networks:
  ntw_consul:
    external: true

volumes:
  vol_consuldata_leader:
  vol_consuldata_replica:

services:
  consul-leader:
    <<: *default-opts
    image: consul:1.5
    command: agent -server -client=0.0.0.0 -bootstrap -ui
    volumes:
      - vol_consuldata_leader:/consul/data
    environment:
      - CONSUL_BIND_INTERFACE=eth0
      - 'CONSUL_LOCAL_CONFIG={"leave_on_terminate": true}'
    networks:
      - ntw_consul
    labels:
      - traefik.frontend.rule=Host:${MY_DOMAIN_CONSUL:-consul.pascalandy.com}
      - traefik.backend=consul-leader
      - traefik.enable=true
      - traefik.port=8500
      - traefik.frontend.auth.basic.users=admin:$2y$05$pAfipn3.brdHMI2eWGnYH.84XYqLozp1sUPi36/l54UAwv.zGLtNC
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
        preferences:
          - spread: node.id
      restart_policy:
        condition: on-failure
        max_attempts: 50
      resources:
        limits:
          cpus: '0.33'
          memory: 96M
        reservations:
          cpus: '0.05'
          memory: 48M

  consul-replica:
    <<: *default-opts
    image: consul:1.5
    command: agent -server -client=0.0.0.0 -retry-join="consul-leader"
    volumes:
      - vol_consuldata_replica:/consul/data
    environment:
      - CONSUL_BIND_INTERFACE=eth0
      - 'CONSUL_LOCAL_CONFIG={"leave_on_terminate": true}'
    networks:
      - ntw_consul
    labels:
        - traefik.enable=false
    deploy:
      mode: replicated
      replicas: ${MY_CONSUL_REPLICAS:-3}
      placement:
        constraints: [node.role == manager]
        preferences:
          - spread: node.id
      restart_policy:
        condition: on-failure
        max_attempts: 50
      resources:
        limits:
          cpus: '0.33'
          memory: 96M
        reservations:
          cpus: '0.05'
          memory: 48M

# inspired by https://github.com/jakubhajek/ntw_consul-swarm
