version: "3.7"

x-default-opts: 
  &default-opts
  logging:
    options:
      max-size: "50m"

networks:
  ntw_consul:
    external: true
  ntw_proxy:
    external: true
  ntw_front:
    external: true

services:

  socat:
    <<: *default-opts
    image: devmtl/socatproxy:1.2
    networks:
      - ntw_proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        max_attempts: 50
      resources:
        limits:
          cpus: '0.20'
          memory: 8M
        reservations:
          cpus: '0.10'
          memory: 4M

  traefik:
    <<: *default-opts
    image: traefik:1.7.12
    command:
      - --api
      - --docker.swarmmode
      - --docker.watch
      - --docker.exposedbydefault=false
      - --docker.swarmModeRefreshSeconds=5
      - --consul.endpoint=consul-leader:8500
      - --docker.endpoint=tcp://socat:2375
      - --accessLog
      - --logLevel=ERROR
      - --metrics
      - --metrics.prometheus
      - --web.address=:8080
      - --defaultentrypoints=http
      #    bypassed to make this stack work out of the box on play-with-docker.com
      #- --defaultentrypoints=http,https
      #- --entrypoints=Name:http Address::80 Redirect.EntryPoint:https
      #- --entrypoints=Name:https Address::443 TLS
      #- --acme
      #- --acme.email=dummy@pascalandy.com
      #- --acme.storage=traefik/acme/account
      #- --acme.entryPoint=https
      #- --acme.httpchallenge.entrypoint=http
      #- --acme.httpchallenge
      #- --acme.onhostrule=true
      #- --acme.acmelogging=true
    networks:
      - ntw_consul
      - ntw_proxy
      - ntw_front
    ports:
    - target: 80
      protocol: tcp
      published: 80
      mode: ingress
    - target: 443
      protocol: tcp
      published: 443
      mode: ingress
    - target: 8080
      protocol: tcp
      published: 8080
      mode: ingress
    deploy:
      mode: replicated
      replicas: ${MY_TRAEFIK_REPLICAS:-3}
      update_config:
        delay: 2s
      placement:
        constraints: [node.role==manager]
        preferences:
          - spread: node.id
      restart_policy:
        condition: on-failure
        max_attempts: 50
      resources:
        limits:
          cpus: '0.33'
          memory: 96M
        reservations:
          cpus: '0.05'
          memory: 48M
      labels:
        - traefik.frontend.rule=Host:${MY_DOMAIN_PROXY:-proxy.pascalandy.com}
        - traefik.enable=true
        - traefik.port=8080
        - traefik.docker.network=ntw_proxy
        - traefik.frontend.auth.basic.users=${MY_AUTH:-admin:$$2y$$05$$1OX5jZ1Kpm/iVKE8tgUhu.STmPkgi0lLxVeP5yEcRioFdV4mcgdTu}

# https://github.com/pascalandy/docker-stack-this
# inspired by https://github.com/jakubhajek/traefik-consul-swarm
# inspired by https://github.com/BretFisher/dogvscat/
# inspired by https://github.com/tiangolo/dockerswarm.rocks