version: "3.7"

services:
  consul-leader:
    image: consul:1.5
    command: agent -server -client=0.0.0.0 -bootstrap -ui
    volumes:
      - consul-data-leader-7:/consul/data
    environment:
      - CONSUL_BIND_INTERFACE=eth0
      - 'CONSUL_LOCAL_CONFIG={"leave_on_terminate": true}'
    networks:
      - ntw_consul
    deploy:
      replicas: 1
      labels:
        # Change this
        - traefik.frontend.rule=Host:${MY_DOMAIN_CONSUL:-consul.pascalandy.com}
        - traefik.backend=consul-leader
        - traefik.enable=true
        - traefik.port=8500
        # Change this (admin/admin)
        - traefik.frontend.auth.basic.users=${MY_AUTH:-admin:$$2y$$05$$1OX5jZ1Kpm/iVKE8tgUhu.STmPkgi0lLxVeP5yEcRioFdV4mcgdTu}

  consul-replica:
    image: consul:1.5
    command: agent -server -client=0.0.0.0 -retry-join="consul-leader"
    volumes:
      - consul-data-replica-7:/consul/data
    environment:
      - CONSUL_BIND_INTERFACE=eth0
      - 'CONSUL_LOCAL_CONFIG={"leave_on_terminate": true}'
    networks:
      - ntw_consul
    deploy:
      replicas: ${MY_CONSUL_REPLICAS:-3}
      placement:
        preferences:
          - spread: node.id
      labels:
        - traefik.enable=false

volumes:
  consul-data-leader-7:
  consul-data-replica-7:

networks:
  ntw_consul:
    external: true

# inspired by https://github.com/jakubhajek/ntw_consul-swarm
