# static configurations
# Updates will require to restart traefik in order to take effect.

log:
  level: INFO

entryPoints:
  dashboard:
    address: :8080
  http:
    address: :80
  https:
    address: :443

api:
  dashboard: true

certificatesResolvers:
  httpchallenge:
    acme:

certificatesResolvers:
  myhttpchallenge:
    acme:
      httpChallenge:
        # used during the challenge
        entryPoint: http
      email: somedomain234982@somedomain.ca
      storage: acme.json
      # uncomment to use Let's Encrypt Staging CA when testing!
      caServer: https://acme-staging-v02.api.letsencrypt.org/directory

providers:
  # https://docs.traefik.io/providers/docker/
  docker:
    network: ntw_front
    exposedByDefault: false
    endpoint: "tcp://127.0.0.1:2375"
    swarmMode: true
    swarmModeRefreshSeconds: "10s"

accessLog: {}
